### ISSUE TITLE
Update translating.md to reflect new translation process

### ISSUE THREAD

**Issue by andylolz** [CodeClub/curriculum_documentation#10]
By the sounds of it, there’s a new translation process. But I’m not sure if [the documentation here](https://github.com/RaspberryPiFoundation/curriculum_documentation/blob/78ad8fd85fc9788bf8c44a64b5ea76aac5b21567/ccw/translating.md) reflects that. It might be handy to update that, and then at least there’s a public reference for the new process.

**Comment by rik-cross** [comment]
Hi Andy, hope you're well! @ninaszymor has made some updates to the documentation, so I'll close this! Thanks :)

**Comment by andylolz** [comment]
Ace – thanks both for addressing this so quickly! The new text is really nice, too.
