### ISSUE TITLE
Guidelines for keeping forks and local copy up to date

### ISSUE THREAD

**Issue by freyjaodds** [CodeClub/curriculum_documentation#3]
In regards to the discussion on https://github.com/CodeClub/curriculum_documentation/pull/2#event-464510048 on how to make the contribution guidelines as clear as possible, is this the best link for guidelines on how to keep a fork and local copy up to date?

https://help.github.com/articles/syncing-a-fork/

I'm using fetch and rebase to keep mine up to date, it has worked for me but I'm not sure if it's the best way and I can't find a link explaining how it makes sense using those commands. 

@martinpeck ?
cc @CodeClubRik

**Comment by andylolz** [comment]
Big +1 for linking to GitHub help for this. Anything sufficiently generic (e.g. how to fork; how to sync) is probably best left to them to write and maintain.

**Comment by freyjaodds** [comment]
Thanks @andylolz. What I'm wondering is if these are the most appropriate guidelines to link to, given that these are not the commands that I use to update my own forks and clones (what I do may or may not be best practice)?

**Comment by andylolz** [comment]
_actually clicks link…_

Mmm okay, I see. So presumably you do something like `git pull origin master`? (that’s what I do, anyway.)

So, `pull` is the same as a `fetch` and a `merge` (which is what they do here). Also, in this example, github have decided to name the remote `upstream` instead of the pretty standard `origin`.

**Comment by freyjaodds** [comment]
I do `fetch CodeClub` and `rebase CodeClub/master` (both before I start making any changes, or just before I `git push`, which I believe updates only my local copy and merges my commit with any changes before I create a pull request... my fork then updates when I create a pull request. Again, this may not be best practice but it has seemed to work so far!

**Comment by martinpeck** [comment]
`upstream` and `origin` mean different things here, which is why they've called it `upstream`

**Comment by andylolz** [comment]
@freyjaodds: Oh yeah, nice. Yeah, that’s a good method, and (I _think_) should never result in weirdness (e.g. merge conflict weirdness).

Funnily enough, with the exception of syncing a fork, you can do all this stuff via the web interface on GitHub (it is super weird that you can’t sync a fork via the web interface.) Have you considered pushing new contributors towards doing everything through the GitHub web interface? It’s really good these days, and doing stuff in your own browser is usually more comfortable than installing new software or using the command line. (and if people prefer the command line, they’ll probably figure out how to do it anyway.)

**Comment by andylolz** [comment]
@martinpeck: they haven’t used `origin` at all in this article. But yeah – if you fork before cloning, then `origin` won’t by default mean “upstream”. (I always clone before forking, so for me, `origin` is synonymous with “upstream”). In any case, I think the decision to be explicit is a good one.

**Comment by martinpeck** [comment]
I suspect that's because the first thing (the "tip") says...

> Before you can sync your fork with an upstream repository, you must configure a remote that points to the upstream repository in Git.

... and points the reader to https://help.github.com/articles/configuring-a-remote-for-a-fork/

**Comment by andylolz** [comment]
Good point, yes. That works fine then – and should fit well with what’s currently here:
https://github.com/CodeClub/curriculum_documentation/blob/master/contributing.md

**Comment by andylolz** [comment]
In sum, then, this GitHub documentation is probably a Good Thing™ to link to.

**Comment by freyjaodds** [comment]
@andylolz about your suggestion to update the fork and local copy via the web interface, I didn't know! All tips to make the process easier for people who aren't web developers are very welcome. 

I found this on updating the fork via the web interface: http://www.hpique.com/2013/09/updating-a-fork-directly-from-github/, but not much on how to update the local copy?

**Comment by andylolz** [comment]
> but not much on how to update the local copy?

So… What I was [suggesting here](https://github.com/CodeClub/curriculum_documentation/issues/3#issuecomment-157098123) was to avoid having a local copy at all. Instead, to get contributors to do everything in their browsers, via the web interface. But of course, while that makes some things simpler (no need to install stuff / use command line) it makes others more complicated (e.g. it means you can’t start from the Project Template). In any case, it’s a bit of a digression from this issue! Apologies for that.

> I found this on updating the fork via the web interface

Yeah good point, you _can_ do it that way… But it’s not ideal for boring reasons that I won’t write about here!

**Comment by martinpeck** [comment]
@freyjaodds as discussed in the past, there's no real alternative. We're using git, and github, for managing these files. Beyond a certain point you can't avoid introducing people to git concepts, they will need to have a local clone of the repository, and they will either need to use the command line or buy themselves a decent git tool that helps them avoid typing the commands.

As @andylolz says, the PR mechanism for updating forks is not recommended. I think I discussed this previously, but it creates a lot of "noise" in the commit history for files.

**Comment by andylolz** [comment]
> the PR mechanism for updating forks is not recommended

It’s a shame github doesn’t offer anything better, though. (Like a “sync fork” button when a fast-forward is possible).

It’s cool you can arbitrarily ‘create’ folders via the web interface:
![awesome project](https://cloud.githubusercontent.com/assets/464193/11237869/229b749c-8dda-11e5-84d7-05ea091c1248.gif)

You can really do a lot with it. The merge commits _are_ messy… But the commit history in these curriculum repos isn’t really clean anyway (and that’s okay – in contrast to a code repo, the history isn’t really that useful).

Losing the Project Template thing seems like it would be a shame, though. It’s tempting to try and create a new project through the web interface, just to see how easy/hard it would be.

**Comment by rikcross** [comment]
From talking to @martinpeck today, we need to ask contributors to...

> [...] do this first (once): https://help.github.com/articles/configuring-a-remote-for-a-fork/
> and then this (each time): https://help.github.com/articles/syncing-a-fork/

These steps are also outlined in this video:
https://www.youtube.com/watch?v=-zvHQXnBO6c

**Comment by freyjaodds** [comment]
Should we update the guidelines with these links then?

**Comment by rikcross** [comment]
Yes @freyjaodds we can do. I'll try to get this done some time soon -- probably next week.

**Comment by rikcross** [comment]
I've added the steps above to the documentation. It's a shame there's no easy way to do upstream merges via the GitHub desktop app, so the command line instructions will have to suffice.
