### ISSUE TITLE
Scratch 1 Paint Box

### ISSUE THREAD

**Issue by SusieWilson** [CodeClub/curriculum_documentation#4]
Hi there,
I wanted to give feedback on the instructions for Paint Box (Scratch 1).  Please could someone take a look at the notes as we all, children and adults alike, struggled to make sense of them, particularly pages 4-6.  Whilst we understand it needs to be challenging, the instructions are really not very clear.  We got there in the end, but the frustration on all sides was palpable (and it's meant to be fun).  Thanks!

**Comment by rik-cross** [comment]
Hi Susie, thanks for getting in touch and for providing feedback. If you're able to let me know the problems encountered then I'd be more than happy to update the resources. The best way to get in touch is to email projects@codeclub.org.uk. Thanks, Rik.
