### ISSUE TITLE
Is it possible contribute with projects based on Java?

### ISSUE THREAD

**Issue by jabrena** [CodeClub/curriculum_documentation#5]
Hi,

I visited the website:
https://codeclubprojects.org/en-GB/contribute/

and I would like to know if it is possible to contribute with projects based on Java.

Many thanks in advance.

Cheers

Juan Antonio

**Comment by rik-cross** [comment]
Hi @jabrena, it's certainly possible, and thanks for offering! Initially it might be a good idea to email projects@codeclub.org.uk with a very short description of some projects you have in mind. That way we can offer support and advice before you write any projects, and ensure that they'll be appropriate for our learners.

Thanks again,
Rik.
