### ISSUE TITLE
Project Checkboxes Stopped Workin

### ISSUE THREAD

**Issue by HarryEMartland** [CodeClub/curriculum_documentation#7]
Hi, I am pretty sure this is the wrong repository but it it the one the CodeClub projects 'Contribute' page points to. The checkboxes seem to have stopped working on the projects pages. I have included some js below which fixes it on the scratch pages. Please could you point me to the correct repository to add this. Thanks

Example page which has stopped working and this js fixes https://codeclubprojects.org/en-GB/scratch/rock-band/

```javascript
$('.lesson-steps > section > section > ul > li').on('click', function () {
    $(this).toggleClass('activity-done');
    window.ga('send', 'event', 'Lesson Step Checkbox', 'clicked');
});
```

**Comment by aldreth** [comment]
@HarryEMartland Thanks very much for pointing this out, it should be fixed now (you may need to clear your browser cache).

I pretty much used your code, but made the selector a little simpler...
```
$('.lesson-steps  li').on('click', function () {
```

Enjoy your Code Clubbing 😄
